
server:
  port: 8081
  error:
    include-message: always
#Configuracion de spring
spring:
  jpa:
    hibernate:
      ddl-auto: update  # o validate, none, etc., según tu caso
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baselineVersion: 1
    locations:
      classpath: db/migration
    sqlMigrationSuffixes: .sql
    baselineOnMigrate: true
    sqlMigrationPrefix: V
    schemas: public

  datasource:
    url: jdbc:postgresql://dpg-d1lgcgh5pdvs73buvlo0-a.oregon-postgres.render.com:5432/neurox
    username: andres
    password: pk9qsEvwghTYjO1ZIFxMDwKkdOhwbOid
    driverClassName: org.postgresql.Driver